# -*- coding: utf-8 -*-
"""Skin final .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7NzBp7kZyB-jBnTh2mjW6MEhT5oPKwE
"""

!pip install kaggle

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
    print('User uploaded file "{name}" with length {length} bytes'.format(
        name=fn, length=len(uploaded[fn])))

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d kmader/skin-cancer-mnist-ham10000

!unzip skin-cancer-mnist-ham10000.zip -d skin-cancer-mnist-ham10000

import pandas as pd
import os

# Dataset path
image_dir = '/content/skin-cancer-mnist-ham10000/'

# Metadata file path
labels_file = os.path.join(image_dir, 'HAM10000_metadata.csv')

# Load CSV file
labels_df = pd.read_csv(labels_file)
# Check dataset loaded correctly
print(labels_df.head())

# Print dataset information
print("Dataset Information:")
print(labels_df.info())

# Get the number of unique classes
num_classes = labels_df['dx'].nunique()
print(f"\nNumber of Classes: {num_classes}")

# Get the class names (abbreviated)
class_names_short = labels_df['dx'].unique()
print("Class Names (Abbreviated):", class_names_short)

# Mapping of short names to full names
class_name_mapping = {
    'bcc': 'basal cell carcinoma',
    'nv': 'melanocytic nevi',
    'mel': 'melanoma',
    'bkl': 'benign keratosis-like lesions',
    'vasc': 'vascular lesions',
    'df': 'dermatofibroma',
    'akiec': 'actinic keratoses & intraepithelial carcinoma'
}

print("\nClass Names (Full):")
for short_name in class_names_short:
    full_name = class_name_mapping.get(short_name, short_name)
    print(f"- {short_name}: {full_name}")

# If you have already run the cell with the LabelEncoder, you can also get class names from it:
# if 'label_encoder' in globals():
#     print("\nClass Names from LabelEncoder:", label_encoder.classes_)

!pip install tensorflow

import pandas as pd
import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define paths
image_dir = '/content/skin-cancer-mnist-ham10000/'
labels_file = os.path.join(image_dir, 'HAM10000_metadata.csv')

# Load labels
labels_df = pd.read_csv(labels_file)
labels_df.head()



import pandas as pd
import os

# Define paths
image_dir = '/content/skin-cancer-mnist-ham10000/'
labels_file = os.path.join(image_dir, 'HAM10000_metadata.csv')

# Load labels
labels_df = pd.read_csv(labels_file)
print("labels_df loaded successfully.")

image_paths = [os.path.join(image_dir, 'HAM10000_images_part_1', img_id + '.jpg')
               for img_id in labels_df['image_id']]
missing_images = [img_path for img_path in image_paths if not os.path.exists(img_path)]

for i in range(len(missing_images)):
    img_id = os.path.basename(missing_images[i]).replace('.jpg', '')
    image_paths[image_paths.index(missing_images[i])] = os.path.join(image_dir, 'HAM10000_images_part_2', img_id + '.jpg')

img_width, img_height = 128, 128
images = []
for img_path in image_paths:
    img = load_img(img_path, target_size=(img_width, img_height))
    img_array = img_to_array(img)
    images.append(img_array)

images = np.array(images)
labels = labels_df['dx'].values

images = images / 255.0

print("Images shape:", images.shape)
print("Labels shape:", labels.shape)

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)

X_train, X_test, y_train, y_test = train_test_split(
    images,
    labels_encoded,
    test_size=0.2,
    random_state=42,
    stratify=labels_encoded
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""**Reasoning**:
Apply data augmentation to the training set.


"""

datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

datagen.fit(X_train)

print("Data augmentation applied to X_train.")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Input
num_classes = len(np.unique(y_train))
model = Sequential([
    Input(shape=(img_width, img_height, 3)),
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(num_classes, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

# Train the model
epochs = 10
batch_size = 32

history = model.fit(datagen.flow(X_train, y_train, batch_size=batch_size),
                    epochs=epochs,
                    validation_data=(X_test, y_test))

# Save trained model
model.save("skin_cancer_model.h5")

# Save label encoder
import pickle
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)

from google.colab import files
files.download("skin_cancer_model.h5")
files.download("label_encoder.pkl")

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print(f"Test Accuracy: {accuracy:.2%}")

from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
from IPython.display import display
from PIL import Image

def predict_skin_disease(image_path, model, label_encoder, img_width, img_height):
    """
    Predicts the skin disease from an input image.

    Args:
        image_path (str): Path to the input image.
        model (tf.keras.Model): Trained deep learning model.
        label_encoder (sklearn.preprocessing.LabelEncoder): Label encoder used for the labels.
        img_width (int): Width of the input images for the model.
        img_height (int): Height of the input images for the model.

    Returns:
        tuple: A tuple containing the predicted class name and the prediction probabilities.
    """
    img = load_img(image_path, target_size=(img_width, img_height))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0
    predictions = model.predict(img_array)
    predicted_class_index = np.argmax(predictions)
    predicted_class_probability = predictions[0][predicted_class_index]
    predicted_class_name_short = label_encoder.inverse_transform([predicted_class_index])[0]
    class_name_mapping = {
        'bcc': 'basal cell carcinoma',
        'nv': 'melanocytic nevi',
        'mel': 'melanoma',
        'bkl': 'benign keratosis-like lesions',
        'vasc': 'vascular lesions',
        'df': 'dermatofibroma',
        'akiec': 'actinic keratoses & intraepithelial carcinoma'
    }
    predicted_class_name_full = class_name_mapping.get(predicted_class_name_short, predicted_class_name_short)


    return predicted_class_name_full, predicted_class_probability, predictions[0], class_name_mapping

def assess_risk(skin_disease_name):
    """
    Provides a simplified, rule-based risk assessment for skin diseases.
    This is not a substitute for medical advice.
    """
    if skin_disease_name in ['melanoma', 'basal cell carcinoma', 'actinic keratoses & intraepithelial carcinoma']:
        return "High"
    elif skin_disease_name in ['benign keratosis-like lesions', 'vascular lesions', 'dermatofibroma']:
        return "Moderate"
    elif skin_disease_name in ['melanocytic nevi']:
        return "Low"
    else:
        return "Unknown"


image_path_input = input("Please enter the path to the image: ")


try:
    img_display = Image.open(image_path_input)
    display(img_display)
except FileNotFoundError:
    print(f"Error: Image file not found at {image_path_input}")
except Exception as e:
    print(f"Error displaying image: {e}")


predicted_class, probability, all_probabilities, class_name_mapping = predict_skin_disease(
    image_path_input, model, label_encoder, img_width, img_height
)

print(f"skin disease found: {predicted_class}")
print(f"Probability of Predicted Class: {probability:.4f}")


risk_level = assess_risk(predicted_class)
print(f"Risk Level: {risk_level}")

print("All Class Probabilities:")
for i, prob in enumerate(all_probabilities):
    class_name_short = label_encoder.inverse_transform([i])[0]
    class_name_full = class_name_mapping.get(class_name_short, class_name_short)
    print(f"- {class_name_full}: {prob:.4f}")

from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
from IPython.display import display
from PIL import Image

def predict_skin_disease(image_path, model, label_encoder, img_width, img_height):
    """
    Predicts the skin disease from an input image.

    Args:
        image_path (str): Path to the input image.
        model (tf.keras.Model): Trained deep learning model.
        label_encoder (sklearn.preprocessing.LabelEncoder): Label encoder used for the labels.
        img_width (int): Width of the input images for the model.
        img_height (int): Height of the input images for the model.

    Returns:
        tuple: A tuple containing the predicted class name and the prediction probabilities.
    """
    img = load_img(image_path, target_size=(img_width, img_height))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0


    predictions = model.predict(img_array)

    predicted_class_index = np.argmax(predictions)
    predicted_class_probability = predictions[0][predicted_class_index]
    predicted_class_name_short = label_encoder.inverse_transform([predicted_class_index])[0]


    class_name_mapping = {
        'bcc': 'basal cell carcinoma',
        'nv': 'melanocytic nevi',
        'mel': 'melanoma',
        'bkl': 'benign keratosis-like lesions',
        'vasc': 'vascular lesions',
        'df': 'dermatofibroma',
        'akiec': 'actinic keratoses & intraepithelial carcinoma'
    }
    predicted_class_name_full = class_name_mapping.get(predicted_class_name_short, predicted_class_name_short)


    return predicted_class_name_full, predicted_class_probability, predictions[0], class_name_mapping

def assess_risk(skin_disease_name):
    """
    Provides a simplified, rule-based risk assessment for skin diseases.
    This is not a substitute for medical advice.
    """
    if skin_disease_name in ['melanoma', 'basal cell carcinoma', 'actinic keratoses & intraepithelial carcinoma']:
        return "High"
    elif skin_disease_name in ['benign keratosis-like lesions', 'vascular lesions', 'dermatofibroma']:
        return "Moderate"
    elif skin_disease_name in ['melanocytic nevi']:
        return "Low"
    else:
        return "Unknown"


image_path_input = input("Please enter the path to the image: ")


try:
    img_display = Image.open(image_path_input)
    display(img_display)
except FileNotFoundError:
    print(f"Error: Image file not found at {image_path_input}")
except Exception as e:
    print(f"Error displaying image: {e}")


predicted_class, probability, all_probabilities, class_name_mapping = predict_skin_disease(
    image_path_input, model, label_encoder, img_width, img_height
)

print(f"skin disease found: {predicted_class}")
print(f"Probability of Predicted Class: {probability:.4f}")


risk_level = assess_risk(predicted_class)
print(f"Risk Level: {risk_level}")

print("All Class Probabilities:")
for i, prob in enumerate(all_probabilities):
    class_name_short = label_encoder.inverse_transform([i])[0]
    class_name_full = class_name_mapping.get(class_name_short, class_name_short)
    print(f"- {class_name_full}: {prob:.4f}")

# =============================
# Save Model and Label Encoder
# =============================

import joblib
from google.colab import files

# Save trained model
joblib.dump(model, "skin_disease_model.pkl")

# Save label encoder


print("Files saved successfully")

# Download files
files.download("skin_disease_model.pkl")